### ISSUE TITLE
AdGuard VPN incompatible with the VoiceOver screen reader

### ISSUE THREAD

**Issue by math65** [AdguardTeam/AdGuardVPNForMac#169] opened 2022-11-17 10:32 UTC
### Issue Details

- **AdGuard VPN version:**
  - 1.2.3.208 release
- **VPN mode:**
  - Off
- **Operating system and version:**
  - Mac OS 13.0.1
- **Other network-level software:**
  - Adguard

### Expected Behavior

The VoiceOver screen reader should see the elements of the interface (Adguard is very accessible for example).

### Actual Behavior

VoiceOver does not see the window or the interface elements. It is impossible to perform an action with the screen reader...

### Screenshots

<details><summary>Screenshot:</summary>

File too big [Download with We transfer](https://we.tl/t-C2cYxmOYXU)

</details>

### Additional Information

I hope this problem will be solved. I am blind, and I have no other solutions to use VoiceOver. Adguard is perfectly accessible, I think you could do the same for VPN. I am available if you need testers, or more information.

Thank you.

**Comment by Versty** [comment] 2022-11-21 10:40
@math65 Hi!
Yes, this feature will be implemented. 

Closed as duplicate of #58

**Closed** 2022-11-21 10:41 UTC
Labels: duplicate, question
